
services:
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432" # Permet de se connecter depuis l'ext√©rieur du conteneur (localhost)
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: registration_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d registration_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  mail:
    image: axllent/mailpit
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP server
    networks:
      - app-network

  api:
    build: .
    networks:
      - app-network
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - SMTP_HOST=mail
      - SMTP_PORT=1025
      - POSTGRES_DB=registration_db
    depends_on:
      db:
        condition: service_healthy
      mail:
        condition: service_started

networks:
  app-network:
    driver: bridge